name: Go Licenses
description: ""

inputs:
  skip-setup:
    description: "skip running setup-go"
    required: false
    default: 'false'
  args:
    description: "additional args for make go-licenses-run"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-go
      if: ${{ inputs.skip-setup == 'false' }}
    - shell: bash
      run: make go-licenses-run ARGS="${{ inputs.args }}"
