# Refer https://github.com/yoheimuta/protolint/blob/master/_example/config/.protolint.yaml
lint:
  ignores: []
  files:
    exclude: []
  directories:
    exclude: []
  rules:
    no_default: true
    add:
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELDS_HAVE_COMMENT
      - ENUM_NAMES_UPPER_CAMEL_CASE
      - ENUMS_HAVE_COMMENT
      - FIELD_NAMES_EXCLUDE_PREPOSITIONS
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - FIELDS_HAVE_COMMENT
      - FILE_HAS_COMMENT
      - FILE_NAMES_LOWER_SNAKE_CASE
      - IMPORTS_SORTED
      - INDENT
      - MAX_LINE_LENGTH
      - MESSAGE_NAMES_EXCLUDE_PREPOSITIONS
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - MESSAGES_HAVE_COMMENT
      - ORDER
      - PACKAGE_NAME_LOWER_CASE
      - PROTO3_FIELDS_AVOID_REQUIRED
      - PROTO3_GROUPS_AVOID
      - QUOTE_CONSISTENT
      - REPEATED_FIELD_NAMES_PLURALIZED
      - RPC_NAMES_CASE
      - RPC_NAMES_UPPER_CAMEL_CASE
      - RPCS_HAVE_COMMENT
      - SERVICE_NAMES_END_WITH
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - SERVICES_HAVE_COMMENT
      - SYNTAX_CONSISTENT
    remove:
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
  rules_option:
    max_line_length:
      max_chars: 120
      tab_chars: 2
    indent:
      style: 2
      not_insert_newline: false
    file_names_lower_snake_case:
      excludes: []
    quote_consistent:
      quote: double
    enum_field_names_zero_value_end_with:
      suffix: ""
    service_names_end_with:
      text: Service
    field_names_exclude_prepositions:
      prepositions: []
      excludes: []
    repeated_field_names_pluralized:
      uncountable_rules: []
      irregular_rules:
        Irregular: Regular
    message_names_exclude_prepositions:
      prepositions: []
      excludes: []
    # rpc_names_case:
    #   convention: upper_snake_case
    messages_have_comment:
      should_follow_golang_style: true
    services_have_comment:
      should_follow_golang_style: true
    rpcs_have_comment:
      should_follow_golang_style: true
    fields_have_comment:
      should_follow_golang_style: true
    enums_have_comment:
      should_follow_golang_style: true
    enum_fields_have_comment:
      should_follow_golang_style: true
    syntax_consistent:
      version: proto3
