name: Buf Lint
description: ""

inputs:
  skip-checkout:
    description: "skip running actions/checkout"
    required: false
    default: "false"
  skip-setup:
    description: "skip running setup-go"
    required: false
    default: "false"
  args:
    description: "additional args for make buf-lint"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      if: ${{ ! inputs.skip-checkout }}
    - uses: .github/actions/setup-go
      if: ${{ ! inputs.skip-setup }}
    - shell: bash
      run: make buf-lint ARGS="${{ inputs.args }}"
