name: Goda Dependency Graph
description: ""

inputs:
  skip-setup:
    description: "skip running setup-go and ts-graphviz/setup-graphviz"
    required: false
    default: 'false'
  args:
    description: "additional args for make goda-run"
    required: false
    default: ""
  artifact-path:
    description: "dependency graph artifact path"
    required: false
    default: "_output/*graph*"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-go
      if: ${{ inputs.skip-setup == 'false' }}
    - uses: ts-graphviz/setup-graphviz@v2
      if: ${{ inputs.skip-setup == 'false' }}
    - shell: bash
      run: make goda-run ARGS="${{ inputs.args }}"
    - uses: actions/upload-artifact@v4
      with:
        name: dependency-graph
        path: ${{ inputs.artifact-path }}
