name: Setup Go
description: ""
inputs:
  go-version:
    description: "go-version for setup-go job"
    required: false
    default: "stable"
  go-version-file:
    description: "go-version-file for setup-go job"
    required: false
    default: ""
  check-latest:
    description: "check-latest for setup-go job"
    required: false
    default: "true"
  cache:
    description: "cache for setup-go job"
    required: false
    default: "false"
  cache-dependency-path:
    description: "cache-dependency-path for setup-go job"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
        check-latest: ${{ inputs.check-latest }}
        cache: ${{ inputs.cache }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
