name: Go Format
description: ""

inputs:
  skip-setup:
    description: "skip running setup-go"
    required: false
    default: "false"
  args:
    description: "additional args for make go-fmt"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: aileron-project/scripts/.github/actions/setup-go@main
      if: ${{ inputs.skip-setup != 'true' }}
    - shell: bash
      run: make go-fmt ARGS="${{ inputs.args }}"
