name: Buf Lint

on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: aileron-project/scripts/.github/actions/buf-lint@main
