name: Check Suite Go

on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: aileron-project/scripts/.github/actions/go-fmt@main

  license:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: aileron-project/scripts/.github/actions/go-licenses@main

  vet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: aileron-project/scripts/.github/actions/go-vet@main

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: aileron-project/scripts/.github/actions/golangci-lint@main

  vulnerability:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: aileron-project/scripts/.github/actions/govulncheck@main
