name: Check Suite Proto

on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

permissions:
  contents: read

jobs:
  proto-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: aileron-project/scripts/.github/actions/protolint@main

  buf-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: aileron-project/scripts/.github/actions/buf-lint@main
