name: Go Test

on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

permissions:
  contents: read 

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 15
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    steps:
      - uses: actions/checkout@v4
      - uses: aileron-project/scripts/.github/actions/setup-go@main
      - uses: aileron-project/scripts/.github/actions/go-test@main
        with:
          go-os: ${{ matrix.os }}
          go-arch: amd64
