name: Golang CI Lint

on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

permissions:
  contents: read 

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: aileron-project/scripts/.github/actions/setup-go@main
      - uses: aileron-project/scripts/.github/actions/golangci-lint@main
