name: Markdownlint

on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install -g markdownlint
      - run: which markdownlint
      - run: markdownlint -h
      - uses: aileron-project/scripts/.github/actions/markdownlint@main
