name: Scan OSS

on:
  workflow_dispatch: {}
  workflow_call: {}
  push: {}

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: aileron-project/scripts/.github/actions/scanoss@main
